### ISSUE TITLE
Create application from template

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#10]
## 📚 Context

Provide a way through the Sunodo CLI to create new applications from scratch.
Today there is a [shell script at the rollups-examples](https://github.com/cartesi/rollups-examples/blob/main/custom-dapps/create-dapp.sh) repo that helps users to create new projects but there are limitations, like generating code for a single language (python).

## ✔️ Solution

We can start with a simple command in the CLI, `sunodo create <dapp> --template <template>`, that creates a directory called `<dapp>` under the current directory, and downloads and copies a template project from a GitHub repository.

## 📈 Subtasks

-   [ ] create a template repository, and at least one template as an example
-   [ ] implement the create command, which downloads code from a remote GitHub repository

## 🎯 Definition of Done

-   [ ] command working and at least one template available
