### ISSUE TITLE
Reference documentation of CLI

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#107]
## 📚 Context

We need to publish the reference documentation of the CLI.
`docs.sunodo.io`, even if we don't have a super nice documentation yet.

## ✔️ Solution

Oclif has all the information necessary to generate documentation, just like it does for the help system of `sunodo --help`.
That help output is crafted for console output though.
While our documentation is written in markdown.

We could just insert the output of the help as a static block of text, but it would be much nicer to build an output in markdown.
We could implement a generation mechanism based on [handlebars](https://handlebarsjs.com) that feed the CLI as handlebars data, and write templates to output nice docs.

## 📈 Subtasks

- [ ] write a generation engine for oclif based on handlebars
- [ ] write handlebars templates to output all the information that is presented by `--help`, but in markdown format
- [ ] auto-generate docs during build into the docs website

## 🎯 Definition of Done

- [ ] documentation beautifully presented at https://docs.sunodo.io/reference/cli/
