### ISSUE TITLE
Reference documentation of contracts

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#108]
## 📚 Context

We have a set or smart contracts to support sunodo dapp deployment.
We should generate reference documentation of those contracts and publish under https://docs.sunodo.io/reference/contracts/

## ✔️ Solution

Use some docs generation of solidity to markdown and add to docs website.
There are a few options of plugins. Do some research and comparison to see which one generates more good looking docs for vitepress markdown engine.

## 📈 Subtasks

- [ ] research solidity docgen options to markdown
- [ ] add generation to the build system to output in the docs website

## 🎯 Definition of Done

- [ ] beautiful documentation available under https://docs.sunodo.io/reference/contracts/

**Comment by tuler** [comment]
For some reason Vercel is not building the reference docs correctly
