### ISSUE TITLE
Build application

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#11]
## 📚 Context

Today Cartesi DApps can use two different [build strategies](https://github.com/cartesi/rollups-examples#build-strategies).
The goal here is to encapsulate the `docker-riscv` build strategy in a CLI command.
This removes build code from the project and move to the CLI, improving the maintainability and upgradability of the process.

## ✔️ Solution

Docker is still a key piece in the process, first because the build starts with a Dockerfile of the application, second because the tools necessary for the build process are usually not installed in the developer machine, like the `cartesi-machine` itself.

There is a way to only require the developer to have Docker installed, and then use pre-built containers that have all the tools necessary for the job.

The job consists of the following steps:

- building the riscv64 DApp image from the Dockerfile
- export the image filesystem as a normalized tar (with dates reset)
- create the ext2 drive of the filesystem from the tar
- boot the machine, using specs coming the some configuration, which can be docker labels
- run until it yields, and save a snapshot

## 📈 Subtasks

- [ ] create a prototype shell script for the job
- [ ] build a docker image with all the necessary tools
- [ ] code the steps in the CLI, using shell calls or, even better, docker calls using dockerode

## 🎯 Definition of Done

-   [ ] build command generating the machine snapshot, or showing errors if any
