### ISSUE TITLE
Automate brew formula release

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#14]
## 📚 Context

The brew formula [references the npm package](https://github.com/sunodo/homebrew-tap/blob/552d6cb6778140c2ba6e0f31f184fd34df9daba9/Formula/sunodo.rb#L6) deployed to npmjs and also has the [sha256 hash](https://github.com/sunodo/homebrew-tap/blob/552d6cb6778140c2ba6e0f31f184fd34df9daba9/Formula/sunodo.rb#L7) of the package.

The update of the brew formula should be automatically update upon release of a new npm package.

## ✔️ Solution

Build a CI strategy on this repo that publishes the npm package, checkout the brew formula, and update it,

## 📈 Subtasks

- [ ] CI script to publish npm package on release
- [ ] CI step to update the brew formula code

## 🎯 Definition of Done

- [ ] brew formula updated on new CLI version, available to the user as `brew upgrade`
