### ISSUE TITLE
Create a sunodo/baseimage container image

### ISSUE THREAD

**Issue by endersonmaia** [sunodo/sunodo#152]
## 📚 Context

So that the Dockerfile from `sunodo/sunodo-template` applications stays simpler, a `sunodo/baseimage` (riscv64) container image could be provided to be used as a base.

## ✔️ Solution

Provide an image with the content from `sunodo/machine-emulator-tools` and `busybox`.

We could take this opportunity to see if there are images that we're building that may not be necessary anymore, and deprecate them.

## 📈 Subtasks

-   [ ] Create a `packages/baseimage` project to build this container image;
-   [ ] Create language images from the baseimage;
-   [ ] Update the `sunodo/sunodo-templates` to use `sunodo/baseimage` and `lanugages`;

## 🎯 Definition of Done

-   [ ] sunodo/baseimage for riscv64 platform published at ghcr.io and docker.io registries 
-   [ ]  `sunodo/{python,nodejs,...}` for riscv64 platform published at ghcr.io and docker.io registries

**Comment by endersonmaia** [comment]
I'm wondering what's the scope intersection with #79

**Comment by tuler** [comment]
There is no intersection with #79.
We will use a Dockerfile in any case to build a cartesi machine.
This Dockerfile will either live in the `sunodo-templates` (and copied to the developer project), or in the `sunodo` CLI, hidden from the developer.

In either case a sunodo base image might be used or not.

**Comment by endersonmaia** [comment]
Going this path would demand us to keep maintaining not just a baseimage but also all language images we'd like to provide over sunodo/sunodo-templates.

So, the strategy was to simplify and stop using sunodo/machine-emulator-tools and install them directly form the cartesi/machine-emulator-tools released binaries.

See https://github.com/sunodo/sunodo-templates/pull/17
