### ISSUE TITLE
Sunodo run with no backend

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#158]
## 📚 Context

The rollups-examples includes a way to run Cartesi applications called [host mode](https://github.com/cartesi/rollups-examples#host-mode). The name is a bit confusing, but it means that the application code run on the host instead of running inside a Cartesi machine.

This is useful to speed up the development process, so the developer doesn't need to build a Cartesi machine and then execute a node.

There are trade-offs in this approach, like hiding the intrincasies of building software for RISC-V or allowing the application to execute outside the Cartesi machine sandbox and do a remote call to the internet. However the prototyping team still feels it's worth the risk.

This feature is implemented in the rollups-examples by replacing the server-manager container by another container using the image `cartesi/rollups-host-runner:1.0.0` instead of the `cartesi/server-manager:0.8.2`.

The `cartesi/rollups-host-runner:1.0.0` does not use the Cartesi machine at all.

## ✔️ Solution

Implement a `sunodo run --no-backend` option that will run the infrastructure of a rollups node that uses the `rollups-host-runner` instead of the `server-manager`.

"No backend" means that the node does not include the application backend. We believe this is a better term than using `host-mode`.

After the rollups-node is up the developer must run his application on his own, that will communicate with the node. He won't use `sunodo` to execute his application.

## 📈 Subtasks

- [ ] Build a rollups-node for this option. This can be a completely different image, or an option of the existing image.
- [ ] Add the `--no-backend` option to the `sunodo run` command

## 🎯 Definition of Done

-   [ ] `sunodo run --no-backend` working

**Comment by tuler** [comment]
Open a new one. But It works for me.

**Comment by endersonmaia** [comment]
> But It works for me.

:thinking: 

Could you share the steps to reproduce it?

**Comment by tuler** [comment]
I tested with a typescript dapp. But the typescript template is broken, and I’m working on a fix.

But it should work with the python one, if that is what you are testing. What logs do you see in the dapp?

**Comment by endersonmaia** [comment]
I tested with typescript template and python from rollups-examples.

The dapp logs just show the `202` HTTP for the `/finish`, and never gets the input, like I saw on previous tests.

```
❯ ROLLUP_HTTP_SERVER_URL="http://127.0.0.1:8080/host-runner" python3 echo.py
INFO:__main__:HTTP rollup_server url is http://127.0.0.1:8080/host-runner
INFO:__main__:Sending finish
INFO:__main__:Received finish status 202
INFO:__main__:No pending rollup request, trying again
INFO:__main__:Sending finish
.... #loop
```

**Comment by tuler** [comment]
Try to run the node in verbose mode to see if the input is being received.

**Comment by oap75** [comment]
@endersonmaia It works for me too. 


![image](https://github.com/sunodo/sunodo/assets/51019382/2f39cfbf-c7b3-4601-bbc6-2a7df382a020)
