### ISSUE TITLE
Run application (locally)

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#16]
## 📚 Context

After the creation of a new application, and the initial build, the user must be able to execute the application locally on his development machine. If the application have not been built, this step could also run the build step automatically.

## ✔️ Solution

The developer must simply execute `sunodo run` and that will perform all the steps necessary to execute the application cartesi node.

The only requirement will be to have Docker installed.

The output of the command is the localhost address where the user can interact with the application.
Several services will be (optionally) exposed to the host machine:

- a postgres database
- a redis database
- an ethereum node (hardhat or anvil)
- a graphql server
- an inspect server
- an explorer web application

## 📈 Subtasks

- [x] #17

## 🎯 Definition of Done

- [x] ability to run a local environment
- [x] ability to shutdown the environment, leaving no trace behind
- [x] access to all exposed services

**Comment by tuler** [comment]
PR #40

**Comment by tuler** [comment]
All done, except for explorer.
Will add that to another issue.
