### ISSUE TITLE
Run linting in the CI

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#168]
## 📚 Context

Even though we have listing configured with prettier and eslint we are not running it in the CI.
This allows dirty code to be merged.

## ✔️ Solution

Run lint procedure in the CI.

## 📈 Subtasks

- [ ] double check linting configuration
- [ ] run linting locally and commit whatever is not conformant
- [x] add linting to CI as a exclusive workflow

## 🎯 Definition of Done

-   [ ] CI breaks if linting check is not green

**Comment by endersonmaia** [comment]
>  add linting to CI as a exclusive workflow

Can you explain it better?

I see two options:

A: run `yarn lint --filter=$paclage` as a step in the current build job
B: run a lint job and make the build depend on its success

If I get it right, by "exclusive worklow¨ you mean option B, right?

**Comment by tuler** [comment]
On B making the build depend on its success has tradeoffs. It increases the total wait time of the CI.

id start with an independent workflow.

**Comment by endersonmaia** [comment]
Just CI was added, there are still other subtasks to be done.
