### ISSUE TITLE
Use rollups node 1.1.0

### ISSUE THREAD

**Issue by endersonmaia** [sunodo/sunodo#222]
## 📚 Context

With the imminent release of cartesi/rollups-node:1.1.0, we should adapt our sunodo/rollups-node release to use the most recent upstream release.

## ✔️ Solution

Adapt the sunodo/rollups-node Dockerfile to use the new sunodo/rollups-node:1.1.0.

## 📈 Subtasks

- [x] Use `PROVIDER_HTTP_ENDPOINT` for `advance-runner`
- [x] Use `POSTGRES_ENDPOINT` instead of `POSTGRES_*` variables
- [x] Use a single container image release with all service binaries
- [x] `state-server`'s `SF_GENESIS_BLOCK` now receives a decimal instead of a hex

## 🎯 Definition of Done

-   [ ] sunodo/rollups-node minor version bump and working
