### ISSUE TITLE
Allow template processing in sunodo create

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#30]
## 📚 Context

Some application templates, currently hosted at https://github.com/sunodo/sunodo-templates, will need some kind of template processing, because some file contents, or even file names will have to follow the application name used during the `sunodo create <name>` command.

## ✔️ Solution

We can use an existing template processing library, like https://handlebarsjs.com, and allow templates to indicate somehow the processing must be done after the template is download from the repo to the developer machine.

## 📈 Subtasks

- [ ] write template processing for file contents
- [ ] write template processing for file name
- [ ] update template to use the new feature
- [ ] document how to write a new template

## 🎯 Definition of Done

- [ ] usage of template processing in the existing and new templates

**Comment by omidasadpour** [comment]
@tuler Could you please provide an example of how the file contents and file name should change? For instance, what placeholders in the file content should be replaced, and how should the file name be modified to reflect the provided application name?

**Comment by tuler** [comment]
As an example, in the [typescript template](https://github.com/sunodo/sunodo-templates/blob/a5a1c16402ce5c620a6cdf7dcf3c5f54db4e9aa8/typescript/package.json#L2) there is the name property in the `package.json` file.
Other templates have a fixed `dapp` name.
