### ISSUE TITLE
Prepare for next cartesi emulator SDK release

### ISSUE THREAD

**Issue by endersonmaia** [sunodo/sunodo#300]
## 📚 Context

Prepare for next emultator SDK release.

## 📈 Subtasks

- [x] ROM got integrated into the emulator (There is no more: `--rom-image`)
- [x] use xgenext2fs binary when version is 1.5.3 instead of genext2fs
- [x] `--rollup` option got removed in favor of being the default. Use `--no-rollup` to disable it instead. (examlpe: https://github.com/sunodo/sunodo/blob/320df7b00c7d2ab80a2beeea782f168188755101/apps/cli/src/commands/shell.ts#L44)
- [x] `--append-rom-bootargs` got renamed to `--append-bootargs` (example: https://github.com/sunodo/sunodo/blob/320df7b00c7d2ab80a2beeea782f168188755101/apps/cli/src/commands/shell.ts#L49)
- [x] `tools.tar.gz` is being removed use `.deb` instead (example: https://github.com/sunodo/sunodo-templates/blob/main/go/Dockerfile#L40)

**Comment by edubart** [comment]
- [ ] New append init commands commands (executed as root privilege before the entrypoint commands). Ideally Sunodo should provide a way to customize the init, because some dapps may want to change folder/devices permissions as root before running the entrypoint.
>   --append-init=<string>
    append a command to machine's init script to be executed with root privilege.
    The command is executed on boot after mounting flash drives and before running the entrypoint.
    You can pass this option multiple times.

>  --append-init-file=<filename>
    like --append-init, but use contents from a file.

- [ ] New append entrypoint commands (executed as dapp privilege before the final dapp command). Ideally Sunodo should provide a way to add customize entrypoint, because some dapps may want to execute additional commands as dapp user before running the final entrypoint command.

>   --append-entrypoint=<string>
    append a command to machine's entrypoint script to be executed with dapp privilege.
    The command is executed after the machine is initialized and before the final entrypoint command.
    You can pass this option multiple times.

>  --append-entrypoint-file=<filename>
    like --append-entrypoint, but use contents from a file.

- [ ] `--append-bootargs` was renamed, ideally Sunodo should provide a way to add extra bootargs, because some dapps may want to enable/disable kernel features before booting.
- [ ] You can now customize the entrypoint user with `--append-init=USER=root`, this replaces the `--append-rom-bootargs='single=yes'`.
- [ ] You can now customize the entrypoint working directory with `--append-init=WORKDIR=/tmp`.
- [ ] You can now set entrypoint environment variables with `--append-entrypoint='export MYVAR=something'`.

- [ ] `-it` option for improved terminal experience was added (colored, support icons, and bigger size), ideally Sunodo should use it, however this depends on `stty` command being available in the host.
>   -it
    run in interactive mode like -i,
    but also sets terminal features and size in the guest to match with the host.
    This option will copy TERM, LANG, LC_ALL environment variables from the host to the guest,
    allowing the use of true colors and special characters when the host terminal supports.

- [ ] `--flash-drive` got the new `mount` and `user` options, ideally Sunodo should have flexibility for setting them in extra flash drives, this only make sense after https://github.com/sunodo/sunodo/issues/193 .
>  mount (optional)
        whether the flash drive should be mounted automatically in init.
        by default, the drive is mounted if there is an image file backing it,
        you can use "mount:false" to disables auto mounting,
        you can also use "mount:<path>" to choose a custom mount point.

> user (optional)
        changes the user ownership of the mounted directory when mount is true,
        otherwise changes the user ownership of the respective /dev/pmemX device,
        this option is useful to allow dapp's user access the flash drive,
        by default the mounted directory ownership is configured by the filesystem being mounted,
        in case mount is false the default ownership is set to the root user.

**Comment by endersonmaia** [comment]
I'm closing this issue, since most of it was implemented at #431 , some other sub issues listed here are not checked but I created another issue (#451) to track.
