### ISSUE TITLE
CLI distribution for Debian/Ubuntu via apt

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#31]
## 📚 Context

Ubuntu and Debian users should have an option to install the Sunodo CLI using `apt-get install sunodo`.

## ✔️ Solution

oclif framework already provides a way to produce artifacts for a debian apt repository.
https://oclif.io/docs/releasing#ubuntudebian-packages

## 📈 Subtasks

- [x] create infrastructure code for a S3 bucket to host cli distributions
- [x] create cloudfront distribution for the S3 bucket, using the domain https://cli.sunodo.io
- [x] create a setup script to allow users to run something like `curl https://sunodo.io/install.sh | sh`
- [x] setup a CI job to do the release

## 🎯 Definition of Done

- [x] Ubuntu users should be able to install and update the CLI using a simple step

**Comment by oap75** [comment]
This issue has done by #49. 
@tuler Need final review .
