### ISSUE TITLE
CLI distribution for macOS as pkg installer

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#32]
## 📚 Context

macOS users who don't use homebrew or macports should be able to install the CLI using a pkg installer.

## ✔️ Solution

oclif framework already provides a way to produce artifacts for a pkg installer
https://oclif.io/docs/releasing#macos-installer

## 📈 Subtasks

- [x] create infrastructure code for a S3 bucket to host cli distributions
- [x] create cloudfront distribution for the S3 bucket, using the domain https://cli.sunodo.io
- [ ] research how to sign the package
- [ ] setup a CI job to do the release

## 🎯 Definition of Done

- [ ] macOS users should be able to install and update the CLI using the installer

**Comment by oap75** [comment]
@tuler Can we use the same S3 bucket that we use for debian ?

**Comment by oap75** [comment]
To sign a macOS package (.pkg file), we need to use the [productsign](https://www.manpagez.com/man/1/productsign/) command-line tool provided by Apple. This tool is used to digitally sign installer packages to ensure their authenticity and integrity. Here's how we can sign a package:

* Obtain an Apple Developer ID:
To sign a package, we need a valid Apple Developer ID certificate. We can obtain this by enrolling in the Apple Developer Program.

* Generate a Developer ID Installer Certificate:
Once we have a Developer ID, we'll need to generate a Developer ID Installer certificate using the Keychain Access app on the macOS machine. This certificate is used to sign the package.

* Sign the Package:
Open Terminal and use the productsign command to sign the package. Replace "Developer ID Installer: Your Developer ID" with the common name of your Developer ID Installer certificate.

```sh
productsign --sign "Developer ID Installer: our Developer ID" /path/to/input.pkg /path/to/signed.pkg
```

* Verify the Signature:
We can verify the signature of the signed package using the spctl command:

```sh
spctl -a -vv /path/to/signed.pkg
```

**Comment by tuler** [comment]
Sunodo should enroll in the Apple Developer Program as an Organization.
https://developer.apple.com/programs/enroll/

But we don't have a D-U-N-S number for Sunodo yet.
So we need to postpone this task.
