### ISSUE TITLE
sunodo doctor command

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#33]
## 📚 Context

Sunodo CLI requires docker to be installed and properly configured.
This is sometimes hard to verify, and errors happen during usage if the system does not meet the minimum requirements.

## ✔️ Solution

Implement a `sunodo doctor` command, similar to `brew doctor` command.
It will verify all the minimal requirements for the proper execution of sunodo commands, tipically:

- check if docker and all necessary subcomponents are installed and running properly
- check the minimal versions of such components

if everything is ok it should print:
```
Your system is ready for sunodo.
```

If it's not ok, it should print the errors.

## 📈 Subtasks

- [x] check if docker is install and running
- [x] check if docker plugins are installed (buildx, compose)
- [x] check if docker can run riscv64 containers

## 🎯 Definition of Done

- [x] print ok if everything is installed and working
- [x] print errors if anything is wrong

**Comment by felipefg** [comment]
I suggest adding "check if docker can run riscv64 containers" as a subtask. This is a requirement for the new build system, and the reason why the build will fail on gitpod.
