### ISSUE TITLE
Upload machine to Pinata

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#338]
## 📚 Context

The `sunodo deploy` command will start by uploading the cartesi machine snapshot of the application to IPFS. It does that using the Kubo RPC API [dag/import](https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-dag-import) endpoint, which is only available at a local IPFS node executed by the developer.

If the developer don't want to run a local IFPS node to publish his machine and instead want to use a third-party IPFS provider than we need to implement another option. If the user wants to use [Pinata](https://www.pinata.cloud) then we need to implement support for its [custom publishing API](https://docs.pinata.cloud/docs/pinata-sdk).

## ✔️ Solution

In the deploy CLI flow we would ask where the user would like to publish the machine to, a local IPFS node, or Pinata.

## 📈 Subtasks

- [ ] modify flow to ask upload destination
- [ ] implement the Pinata upload

## 🎯 Definition of Done

- [ ] upload to Pinata working
