### ISSUE TITLE
deprecate sunodo/sdk and use sunodo/rollups-node as builder and runner image

### ISSUE THREAD

**Issue by endersonmaia** [sunodo/sunodo#356]
## 📚 Context

Today we maintain two container images with different purposes, `sunodo/rollups-node` is used by `sunodo run` command to execute the validator node for the application, and `sunodo/sdk` that's used by `sunodo build`  to build the application machine snapshot.

It's nice to have specialized container images but when it comes to keep things compatible between `build` and `run` it's easy to mess things up.

One can have an snapshot built with a different `sunodo` version and try to run with more recent version and they may not match.

## ✔️ Solution

I propose that we deprecate the usage of `sunodo/sdk` and use the `sunodo/rollups-node` as a single image that's ready to build and run applications.

So the command `build`, `run` and `shell` can use the same image and avoid incompatibility issues.

## 📈 Subtasks

-  [ ] remove references to sunodo/sdk
-  [ ] embbed into sunodo/rollups-node all the necessary to run the snapshot build process

## 🎯 Definition of Done

-   [ ]  a new version os sunodo/rollups-node and sunodo/cli

**Comment by tuler** [comment]
Yes. With the transition to Cartesi CLI the image will probably be `cartesi/sdk` or something like that.
