### ISSUE TITLE
Do not require Docker for root filesystem construction

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#366]
## 📚 Context

Sunodo CLI build command uses Docker to build the root filesystem of the user application, by following the steps below:

1) application defines a Dockerfile that builds as the final image of a multi-stage build a RISC-V runtime image containing the application code and whatever it need to work. [Docker RISC-V support](https://medium.com/@tonistiigi/early-look-at-docker-containers-on-risc-v-40ed43b16b09) through QEMU emulation helps a lot because it avoids having to deal with cross-compilation to RISC-V, which is very convenient.

2) a docker is created using `docker container create` and exported using `docker container export`, which create a `.tar` file with the filesystem contents.

3) `tar` is then used to "cleanup" the `.tar` created by Docker, and remove files which may lead to irreproducibility.

4) A `.ext2` drive is created from the `.tar` file

5) A Cartesi machine is created using the `.ext2` file and other files like the Linux kernel. Machine is booted until it yields for the first time, then saved to a snapshot.

## ✔️ Solution

There will be more alternatives to build the application root filesystem after the [VirtIO support](https://github.com/cartesi/machine-emulator/issues/38) is released.

Users will be able to interactively use the Cartesi machine, including network connectivity and host file system access, for prototyping and also for building the resulting root filesystem.

We need to start exploring these alternatives after that is available.

## 📈 Subtasks

- [ ] explore how VirtIO works and how it can be leveraged for this task
- [ ] adapt Sunodo CLI to the new emulator version

## 🎯 Definition of Done

- [ ] build a root filesystem without using Docker

**Comment by tuler** [comment]
Moved to https://github.com/cartesi/cli/issues/71
