### ISSUE TITLE
Sunodo CLI dependency on Docker

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#367]
## 📚 Context

Docker is a complex software that brings a lot of value, but also a lot of problems to end-users. Different installation methods have different nuances. We like to recommend Docker Desktop to all users, but some of them do not use for one reason or another.

The Sunodo CLI uses Docker for two different things:

1) help build the application root filesystem;
2) execute binaries during application build and node execution that are not available in the host system

## ✔️ Solution

To reduce or completelly eliminate the dependency on Docker, the two use cases above must be addressed.
The issues below follow them independently.

## 📈 Subtasks

- [ ] https://github.com/sunodo/sunodo/issues/366
- [x] https://github.com/sunodo/sunodo/issues/332

## 🎯 Definition of Done

- [ ] not depend on Docker for Sunodo CLI

**Comment by endersonmaia** [comment]
We also use docker and compose for `sunodo run` to start dependencies like traefik, anvil, subsquid, PostgreSQL.

**Comment by tuler** [comment]
https://github.com/cartesi/cli/issues/70
