### ISSUE TITLE
Move from yarn classic to a better package manager

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#368]
## 📚 Context

We are still using yarn classic.
There are better alternatives nowadays.
Either latest npm, pnpm, or yarn modern.

They are all faster and provide a better user experience.

## ✔️ Solution

Choose between the three mentioned and migrate away from yarn classic.
Maybe test more than one, and evaluate what works best.
I had a good experience with pnpm.

## 📈 Subtasks

- [x] #370
- [ ] evaluate yarn modern
- [ ] evaluate latest npm
- [ ] migrate away from yarn classic

## 🎯 Definition of Done

- [x] new and faster package resolution mechanism

**Comment by tuler** [comment]
Migrated to pnpm without evaluating others. It's good enough.
