### ISSUE TITLE
Web3 payment system and node controller

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#37]
## 📚 Context

Running nodes for DApps has infrastructure costs, and transactions costs.
Infrastructure costs are typically charged in USD (or other fiat) by cloud providers.
Transactions costs are charged in the base layer coin, which can be ETH in case of Ethereum mainnet, or other layer-2 networks coin.

Infrastructure costs can be paid through traditional web2 system (credit cards), or web3, using ERC-20.
There are multiple ERC-20 stable coins to choose from if charges must keep a USD value.

A payment system must be designed and deployed to a live network that keep records of funding of DApps.
Those DApps can be deployed on the same network as the payment system, or can be deployed to a different network, like a testnet. Even for testnet DApps, the payment system itself must be running on a live network, because it need to charge real "money".

## ✔️ Solution

Implement smart contracts to handle funding of DApps.
Anyone would be able to create a "vault" with:

- the address of the dapp
- the chainId of the dapp
- the recipient of the funds

Then create an offchain code, the controller, that tracks deposits to the vaults and create a table with the following information:

```
dapp_address
dapp_chainId
shutdown_date
```

The shutdown date marks until when the dapp has enough funds to continue working, based on funds deposited and also withdraws taken by the recipient. The value gets updated whenever there is a new deposit, by listening to events of the smart contract.

## 📈 Subtasks

- [ ] implement smart contract for the system
- [ ] implement a controller to keep track of dapps funding

## 🎯 Definition of Done

-   [ ] have a table with shutdown dates of dapps nodes

**Comment by tuler** [comment]
PR #44 
PR #45

**Comment by tuler** [comment]
Work in progress in PR #45 

There is a simple database with a single table, that holds information of DApps, its machine locations and financial runway.
This database was implemented using prisma, with a sqlite backend.
The sqlite will be stored, by default, in the data dir of the sunodo CLI.
The database access in the application was abstracted using a `NodeDatabase` typescript interface, so we can switch from prisma to another simpler framework if we feel so.

The launching of DApp nodes will be controlled by "drivers" and the typescript interface `NodeDriver`.
We have to implement initially a `docker` or `compose` provider that uses the `rollups-node` docker image to launch nodes.
We will implement the possibility of running several dapps in the same machine, with a single container for the following services:

- anvil (if private net)
- redis
- postgres
- traefik (router)

Launched nodes for dapps will be routed by a traefik running at `http://localhost:8080` so users can access their dapps (graphql, inspect) by appending a path to the URL with the dapp address.

**Comment by tuler** [comment]
The latest implementation of the controller is a little different from what is describe in the message above.

1) instead of using a SQL database, the information is held on memory and serialized to a json file if the process ends. This json file is loaded when the controller restarts so it can start from where it stopped (keeping track of the chain block number).

2) instead of implementing different drivers we decided to focus now on Kubernetes only. The controller simply creates a k8s custom resource for the application, which is used by a Kubernetes operator to create the necessary docker containers for that application.
