### ISSUE TITLE
Revisit how we are doing the ENS integration of ValidatorNodeProvider

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#374]
## 📚 Context

We are currently not using the [ReverseClaimer](https://github.com/ensdomains/ens-contracts/blob/master/contracts/reverseRegistrar/ReverseClaimer.sol) contract as instructed in the [ENS documentation](https://docs.ens.domains/web/naming-contracts).

## ✔️ Solution

Learn more about the proper method and switch to the appropriate implementation.

## 📈 Subtasks

- [ ] learn more about ENS ReverseClaimer.sol
- [ ] change the implementation if needed

## 🎯 Definition of Done

- [ ] use of ReverseClaimer.sol
