### ISSUE TITLE
Add instantiation of required contracts to sunodo/devnet

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#381]
## 📚 Context

Rollups 1.0 used to have an Authority and a History contract already deployed and included in the npm package.
Those contracts are necessary to run a node.

Rollups 1.2 does not include those contract any longer. It's a responsibility of the node runner to deploy those contracts prior to running a node.

The devnet environment could do that for the user, and have a docker image with anvil ready to be used by a local development environment.

The upcoming marketplace feature will also need a ValidatorNodeProvider contract instantiated.

## ✔️ Solution

Write a hardhat task in the devnet project that instantiates the required contracts.
Call that task during build to produce the anvil dump we are baking into a docker anvil image.
We also need to store the address of the contracts in some way inside the image.

## 📈 Subtasks

- [x] #384
- [x] write a task to instantiate a ValidatorNodeProvider
- [x] modify build process to call the tasks

## 🎯 Definition of Done

- [x] sunodo/devnet image has information about instantiated contracts
