### ISSUE TITLE
Deploy for self-hosting

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#383]
## 📚 Context

The deployment system designed in issue https://github.com/sunodo/sunodo/issues/18 focus on the developer using a third-party provider as the validator.

This requires a financial incentive mechanism and a Cartesi machine distribution method. This is covered by the Marketplace as the financial incentive mechanism, and IPFS as distribution channel.

But there is a scenario where the developer is self-hosting his application node, or he enters in a private agreement with someone else outside the marketplace.

In this case we can simplify the deployment process, by not using a ValidatorNodeProvider and not using IPFS to distribute the Cartesi machine.

The onchain deployment can call directly the `CartesiDAppFactory` smart contract, and the machine can be handed over to the node runner however they prefer.

## ✔️ Solution

The diagram below show the deployment procedure through the Marketplace.

![deploy-third-party](https://github.com/sunodo/sunodo/assets/73850/3c7396ef-64db-4971-9a2f-250de9a2056d)

The diagram below show the deployment procedure without the Marketplace.
The developer using the deployment UI talks directly to the CartesiDAppFactory contract to deploy the application onchain counterpart. He then sends the corresponding Cartesi machine to the node, however he wants. No payment is involved.

![deploy-self-hosted](https://github.com/sunodo/sunodo/assets/73850/3ed0cbac-585b-4623-9fb8-ad7b24a637bd)

## 📈 Subtasks

- [x] implement an alternative flow in the Web UI that goes directly to the CartesiDAppFactory.
- [x] implement a running mode of the `sunodo-node` that does not watch the Marketplace and does not download the Cartesi machine from IPFS. Application address is specified explicitly and machine is expected to be on disk.

## 🎯 Definition of Done

- [x] deploy workflow for self-hosting working
