### ISSUE TITLE
Add a command that prints out the template hash

### ISSUE THREAD

**Issue by guidanoli** [sunodo/sunodo#390]
## 📚 Context

Post-build, the image hash is stored in the `.sunodo/image/hash` file in binary format.
For most use cases, however, a hexadecimal format is more useful.
This hash can be displayed in this format by running the following command.

```sh
xxd -c 32 -p .sunodo/image/hash
```

This might not be very intuitive for beginner developers, though.

## ✔️ Solution

Add a new command, e.g. `sunodo hash`, which prints the machine hash in hexadecimal format (also, prefixed by `0x`). The `xxd` utility should not be necessary.

## 📈 Subtasks

-   [ ] Add a `sunodo hash` command
-   [ ] Mention the command in the documentation
-   [ ] Test the command against the traditional method
-   [ ] Test the command when no image has been built yet
-   [ ] Test the command when the image was built but the `hash` file is missing

## 🎯 Definition of Done

-   [ ] The command was added
-   [ ] The command was documented
-   [ ] The command was tested
