### ISSUE TITLE
Migrate from Sunodo CLI to Cartesi CLI

### ISSUE THREAD

**Issue by endersonmaia** [sunodo/sunodo#404]
This issue is meant to group all the effort needed to migrate to the future https://github.com/cartesi/cli project.

- [x] #447
- [x] #445
- [x] https://github.com/sunodo/sunodo/pull/493
- [ ] ~~Define owner and repository to hold cartesi marketplace smart contracts~~
- [x] Create `cartesi/application-templates` for `cartesi create` command
- [x] Publish @cartesi/cli@0.14.0
- [x] Publish brew formula at https://github.com/cartesi/homebrew-tap
- [x] https://github.com/cartesi/docs/pull/183
- [x] https://github.com/sunodo/sunodo/pull/492
- [x] https://github.com/sunodo/sunodo/pull/495

For context: 

- https://governance.cartesi.io/t/sunodo-a-cartesi-convenience-layer/370/2?u=endersonmaia
- https://twitter.com/SunodoProject/status/1759578710599241986

**Comment by tuler** [comment]
Consider a version where the transition will happen. I'll call it here 0.13, but it may change.
On the user's perspective, this is what would happen.

User upgrades sunodo to 0.13.
Any command he makes (sunodo create, sunodo build, etc) prints the following message:

```
DEPRECATED: Sunodo CLI is now Cartesi CLI.
Uninstall Sunodo CLI by following the documentation at https://docs.sunodo.io/guide/introduction/installing;
Install Cartesi CLI by following the documentation at https://docs.cartesi.io/cartesi-rollups/1.3/development/installation/
```

Cartesi CLI publishes a 0.14 version that has everything pre-sunodo 0.13.

Here is how we can make the code transition.
Cartesi forks the Sunodo repo. On top of main@0.13 it reverts the changes that removed the commands functionality (which were replaced to add the DEPRECATION message). It adds changes to whatever it needs to publish the packages as `@cartesi`. And publishes a `@cartesi/cli@0.14`.

**Comment by endersonmaia** [comment]
> Cartesi forks the Sunodo repo

I suggest that we transfer so we don't lose issues and stuff.

https://github.com/sunodo/sunodo/issues/447#issue-2233080766

**Comment by tuler** [comment]
## These are the current packages and their internal dependencies:

```
├── apps
│   ├── cli
│   ├── docs
│   └── web
└── packages
    ├── car-download
    ├── contracts
    ├── devnet
    ├── eslint-config
    ├── sdk
    └── tsconfig
```

```mermaid
graph TD;
    cli:::cartesi-->devnet;
    cli:::cartesi-->sdk;
    sdk-->devnet;
    car-download;
    contracts;
    web-->devnet;
    docs;
    car-download-->eslint-config;
    cli:::cartesi-->eslint-config;
    web-->eslint-config;
    cli:::cartesi-->tsconfig;
    devnet-->tsconfig;
    web-->tsconfig;
    classDef cartesi fill:#cyan;
    classDef sunodo fill:#purple;
```

After the fork:

## cartesi/cli

```
├── apps
│   └── cli
└── packages
    ├── devnet
    ├── eslint-config
    ├── sdk
    └── tsconfig
```

```mermaid
graph TD;
    cli-->devnet;
    cli-->sdk;
    sdk-->devnet;
    cli-->eslint-config;
    cli-->tsconfig
    devnet-->tsconfig
```

## sunodo

```
├── apps
│   ├── docs (deprecate with introduction of CLI to https://docs.cartesi.io
│   └── web
└── packages
    ├── car-download (possible future work)
    ├── contracts (possible future work)
    ├── eslint-config
    └── tsconfig
```

```mermaid
graph TD;
    car-download;
    contracts;
    web-->devnet;
    docs;
    car-download-->eslint-config;
    web-->eslint-config;
    web-->tsconfig
```

**Comment by tuler** [comment]
Manually published `@cartesi/devnet@1.6.0` npm package.
https://www.npmjs.com/package/@cartesi/devnet

**Comment by tuler** [comment]
SDK docker image 0.6.0 manually published
https://hub.docker.com/repository/docker/cartesi/sdk/general

**Comment by tuler** [comment]
Repository created https://github.com/cartesi/application-templates

Draft create of what will be the `main` of https://github.com/cartesi/application-templates
https://github.com/sunodo/sunodo-templates/pull/39

**Comment by tuler** [comment]
npm package published
https://www.npmjs.com/package/@cartesi/cli

**Comment by tuler** [comment]
brew formula published
https://github.com/cartesi/homebrew-tap/blob/main/Formula/cartesi.rb
