### ISSUE TITLE
Deprecate sunodo/rollups-node in favor of using cartesi/rollups-node directly

### ISSUE THREAD

**Issue by endersonmaia** [sunodo/sunodo#411]
## 📚 Context

We have a sunodo/rollups-node because we added a lot of other tools to make cartesi/rollups-node run in a single container and other stuff.

Since the release of cartesi/rollups-node:1.3.0, with the go-supervisor functionality, we don't need to manage the internal services anymore, and the sunodo/rollups-node has only the rollups-node service and a snapshot-provisioner script.

## ✔️ Solution

We should use cartesi/rollups-node container image directly from sunodo/cli and deprecate de usage of sunodo/rollups-node.

## 📈 Subtasks

-   [x] Change sunodo/cli to use cartesi/rollups-node container image
-   [x] Make snapshot provisioning

## 🎯 Definition of Done

-   [x] When sunodo/cli doesn't depends on sunodo/rollups-node anymore
