### ISSUE TITLE
sunodo build code has to many execa calls

### ISSUE THREAD

**Issue by endersonmaia** [sunodo/sunodo#415]
## 📚 Context

`sunodo build` relyes on `docker run` using `sunodo/sdk`, and all calls to `docker run` are made with` exeac`.

The code is very intricate and verbose, since we build the commands inside an array and have to mass parameters to `docker` and some times to programs inside the container, like `cartesi-machine`

## ✔️ Solution

We could encapsulate some of those commands inside shell scripts already inside the sunodo/sdk, and call those scripts from `sunodo build` code with a simpler `exaca` call.

## 📈 Subtasks

-   [ ] Add common build scripts to sunodo/sdk
-   [ ] Call sunood/sdk scripts from `sunodo build` command code.

## 🎯 Definition of Done

-   [ ] sunodo/sdk patch released with build scripts embeded
-   [ ] `sunodo build` code simpler to read and maintain
