### ISSUE TITLE
Reduce CLI installation size

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#432]
## 📚 Context

Installing @sunodo/cli, either through `npm install` or `brew install` download the npm package all install all its dependencies.
The total size of the package installation for sunodo 0.11.2 is currently at ~280Mb.

```shell
npx howfat -r table @sunodo/cli
@sunodo/cli@0.11.2 (983 deps, 279.47mb, 46078 files, ©Apache-2.0)
```

This is huge in my opinion.
After analyzing the above complete log of `npx howfat @sunodo/cli`, some aggressors are clear:

```
╭─────────────────────────────────────────┬──────────────┬──────────┬───────┬───────────┬──────────────┬───────────╮
│ Name                                    │ Dependencies │     Size │ Files │ Native    │ License      │ Deprec    │
├─────────────────────────────────────────┼──────────────┼──────────┼───────┼───────────┼──────────────┼───────────┤
│ @inquirer/prompts@4.3.1                 │           44 │   3.19mb │   526 │           │ MIT          │           │
├─────────────────────────────────────────┼──────────────┼──────────┼───────┼───────────┼──────────────┼───────────┤
│ @ledgerhq/hw-app-eth@6.35.7             │          119 │ 102.95mb │ 13397 │           │ Apache-2.0   │           │
├─────────────────────────────────────────┼──────────────┼──────────┼───────┼───────────┼──────────────┼───────────┤
│ @ledgerhq/hw-transport-node-hid@6.28.5  │           58 │  15.88mb │  4446 │           │ Apache-2.0   │           │
├─────────────────────────────────────────┼──────────────┼──────────┼───────┼───────────┼──────────────┼───────────┤
│ @metamask/sdk@0.18.2                    │          169 │  60.38mb │ 12355 │           │              │           │
├─────────────────────────────────────────┼──────────────┼──────────┼───────┼───────────┼──────────────┼───────────┤
│ @oclif/core@3.26.0                      │           94 │   6.44mb │  1327 │           │ MIT          │           │
├─────────────────────────────────────────┼──────────────┼──────────┼───────┼───────────┼──────────────┼───────────┤
│ @oclif/plugin-help@6.0.20               │           95 │   7.04mb │  1337 │           │ MIT          │           │
├─────────────────────────────────────────┼──────────────┼──────────┼───────┼───────────┼──────────────┼───────────┤
│ @oclif/plugin-plugins@5.0.5             │          334 │  28.83mb │  6074 │           │ MIT          │           │
├─────────────────────────────────────────┼──────────────┼──────────┼───────┼───────────┼──────────────┼───────────┤
│ @oclif/plugin-update@4.2.3              │          189 │  15.25mb │  5448 │           │ MIT          │           │
├─────────────────────────────────────────┼──────────────┼──────────┼───────┼───────────┼──────────────┼───────────┤
│ @walletconnect/ethereum-provider@2.12.0 │          266 │  47.56mb │  6402 │           │ Apache-2.0   │           │
├─────────────────────────────────────────┼──────────────┼──────────┼───────┼───────────┼──────────────┼───────────┤
│ lokijs@1.5.12                           │              │   2.93mb │    32 │           │ MIT          │           │
├─────────────────────────────────────────┼──────────────┼──────────┼───────┼───────────┼──────────────┼───────────┤
│ node-fetch@3.3.2                        │            5 │   8.81mb │   126 │           │ MIT          │           │
╰─────────────────────────────────────────┴──────────────┴──────────┴───────┴───────────┴──────────────┴───────────╯
```

## ✔️ Solution

Some features could be removed, like WalletConnect, Metamask and Ledger support.
Oclif can be replaced with another lighter framework.
We could use specific Inquirer packages that we need.
Some of the packages above are not even being used.

## 📈 Subtasks

- [ ] https://github.com/sunodo/sunodo/issues/428
- [x] https://github.com/sunodo/sunodo/pull/434

## 🎯 Definition of Done

- [ ] package download size extremely reduced

**Comment by tuler** [comment]
https://github.com/cartesi/cli/issues/11
