### ISSUE TITLE
sunodo shell|build passthrough some CLI arguments

### ISSUE THREAD

**Issue by endersonmaia** [sunodo/sunodo#451]
## 📚 Context

The `cartesi-machine` command provides a series of CLI arguments that controls the machine execution during the build of the snapshot of interactive mode.

## ✔️ Solution

It should be possible to passthrough some (or all) `cartesi-machine` CLI arguments via `sunodo [build|shell]`.

For ex.: 

```shell
sunodo shell --append-entrypoint='export MYVAR=something'
Running in interactive mode!

         .
        / \
      /    \
\---/---\  /----\
 \       X       \
  \----/  \---/---\
       \    / CARTESI
        \ /   MACHINE
         '

dapp@cartesi-machine:~$ echo $MYVAR
something
```
## 📈 Subtasks

-   [ ] Decide which `cartesi-machine` CLI arguments should be made available to sunodo [shell|build] and add to this issue's subtasks
-   [ ] Add `--append-entrypoint[-file]`
-   [ ] Add `--append-init[-file]`
-   [ ] Add `--append-bootargs`
-   [ ] Add `--flash-drive`

## 🎯 Definition of Done

-   [ ] All defined commands implemented

**Comment by endersonmaia** [comment]
Related to #193.

**Comment by tuler** [comment]
I think we need to think well about how to expose the complexities of the cartesi-machine to the end-user.
If it's an advance user he doesn't even need to use sunodo.

**Comment by endersonmaia** [comment]
> I think we need to think well about how to expose the complexities of the cartesi-machine to the end-user. If it's an advance user he doesn't even need to use sunodo.

That's why I choose only the "simple" ones that are used to inject parameters into the machine.
