### ISSUE TITLE
Add explorer to `sunodo run`

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#76]
## 📚 Context

The `sunodo run` command run a node with GraphQL and Inspect services.
It would be great to also add the explorer.

## ✔️ Solution

Use the Docker image provided by the Explorer team and add to the compose file of `sunodo run`.
We should make it route through traefik (port 8080).
It would be good to make it optional through a command line arg.

## 📈 Subtasks

- [x] add service to docker-compose
- [ ] add flag for services

## 🎯 Definition of Done

-   [x] run an application and see the explorer at http://localhost:8080/explorer

**Comment by tuler** [comment]
Included in sunodo 0.9.0
