### ISSUE TITLE
Run the whole infrastructure locally

### ISSUE THREAD

**Issue by endersonmaia** [sunodo/sunodo#8]
## 📚 Context

It should be possible to run the whole infrastructure locally to help on the development process and possibly leverage the same for automated integration tests.

Since we don't plan to have a remote development environment, we should make the local environment as close as possible to the remote production environment.

## ✔️ Solution

Use `docker-compose.yaml` to bundle the components necessary to run the remote infrastructure locally.

## 📈 Subtasks

- [ ] Create Dockerfile for each component of the infrastructure
- [ ] Create docker-compose.yaml to bundle all the componentes
- [ ] Create the documentation on how to use this to develop and test

## 🎯 Definition of Done

-   [ ] When the code and documentation steps are enough to run everything locally similar to what we have remotely, it should be considered as done.
