### ISSUE TITLE
Improve log of sunodo run

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#80]
## 📚 Context

The `run` command already has a `verbose` option, which is printing the entire `INFO` level log of the `rollups-node` and other services used by the node like `anvil`, `postgres`, `redis`.

When the log is suppressed, which is the default option`, only the status of the docker containers are shown, and no other log from the services are shown.

Ideally the non-verbose option should still show logs printed by the application itself, which goes through the server-manager component of the `rollups-node`.

## ✔️ Solution

The current implementation of the non-verbose mode launches a docker compose project in detached mode, and wait for it to be healthy. This makes the log to not be piped into sunodo CLI.

Instead of running in detached mode we should run in foreground mode, and control the log variables already available in the internal components, like `RUST_LOG`, `SERVER_MANAGER_LOG_LEVEL` and `REMOTE_CARTESI_MACHINE_LOG_LEVEL`.

## 📈 Subtasks

- [x] change back to running docker compose in foreground mode
- [x] analyze the best configuration for internal compose services
- [x] tweak the `--verbose` option

## 🎯 Definition of Done

- [x] `sunodo run` must be very silent, printing only whatever is printed from inside the application (in the cartesi machine)
- [x] `sunodo run --versobse` must remain the roughly the same
